spring:
  application:
    name: gateway-service
  profiles:
    active: local
  cloud:
    gateway:
      routes:
      - id: school-service
        uri: lb://school-service
        predicates:
        - Path=/school-service/**
      - id: student-info-service
        uri: lb://student-info-service
        predicates:
        - Path=/student-info-service/**
  zipkin:
    message-timeout: 10000
    check-timeout: 10000
#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: ${eureka.instance.hostname}:${server.port}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    status-page-url-path: /actuator/health
    
logging:
  level:
    '[org.springframework.cloud.gateway]': DEBUG
    
management:
  endpoints:
    web:
      exposure:
        include: '*'